name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: eloquent,
             ROS_REPO: main,
             ROSDEP_SKIP_KEYS: "bullet3 fcl ompl tesseract tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_support tesseract_urdf tesseract_visualization",
             CLANG_FORMAT_CHECK: file,
             CLANG_FORMAT_VERSION: 8,
             DOCKER_IMAGE: "mpowelson/tesseract:eloquent",
             AFTER_INIT: "apt-get upgrade -y",
             BADGE: clang-format}
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: eloquent,
             ROS_REPO: main,
             UPSTREAM_WORKSPACE: 'dependencies.rosinstall',
             ROSDEP_SKIP_KEYS: "bullet3 fcl ompl tesseract tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_support tesseract_urdf tesseract_visualization",
             DOCKER_IMAGE: "mpowelson/tesseract:eloquent",
             AFTER_INIT: "apt-get upgrade -y",
             BADGE: clang-tidy,
             NOT_TEST_BUILD: true,
             UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug",
             TARGET_CMAKE_ARGS: "-DTESSERACT_ENABLE_CLANG_TIDY=ON -DTESSERACT_ENABLE_TESTING=ON"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
  test:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: eloquent,
             ROS_REPO: main,
             UPSTREAM_WORKSPACE: 'dependencies.rosinstall',
             ROSDEP_SKIP_KEYS: "bullet3 fcl ompl tesseract tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_support tesseract_urdf tesseract_visualization",
             DOCKER_IMAGE: "mpowelson/tesseract:eloquent",
             AFTER_INIT: "apt-get upgrade -y",
             BADGE: bionic,
             UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug",
             TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_TESTING=ON"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
